<?php

namespace Database\Seeders;

use App\Models\Benefit;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BenefitSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Benefit::insert([
            [
                'language' => 'english',
                'section' => 'heading',
                'heading_eng' => "Membership Benefits",
                'sub_heading_eng' => "Discover the comprehensive advantages that set Supertrade apart from traditional business solutions",
                'image' => null,
                'icon' => null,
                'card_title_eng' => null,
                'card_description_eng' => null,
                'card_btn_text_eng' => null,
                'newsletter_title_eng' => null,
                'newsletter_sub_title_eng' => null,
                'newsletter_btn_text_eng' => null,
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'card_title_fr' => null,
                'card_description_fr' => null,
                'card_btn_text_fr' => null,
                'newsletter_title_fr' => null,
                'newsletter_sub_title_fr' => null,
                'newsletter_btn_text_fr' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'france',
                'section' => 'heading',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'image' => null,
                'icon' => null,
                'card_title_eng' => null,
                'card_description_eng' => null,
                'card_btn_text_eng' => null,
                'newsletter_title_eng' => null,
                'newsletter_sub_title_eng' => null,
                'newsletter_btn_text_eng' => null,
                'heading_fr' => "Avantages de l'adhésion",
                'sub_heading_fr' => "Découvrez les avantages complets qui distinguent Supertrade des solutions commerciales traditionnelles.",
                'card_title_fr' => null,
                'card_description_fr' => null,
                'card_btn_text_fr' => null,
                'newsletter_title_fr' => null,
                'newsletter_sub_title_fr' => null,
                'newsletter_btn_text_fr' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'english',
                'section' => 'card',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'image' => "https://superinternaute.netlify.app/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fmember1.13b38952.jpg&w=640&q=100",
                'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-trending-up md:w-10 md:h-10 w-6 h-6" aria-hidden="true"><path d="M16 7h6v6"></path><path d="m22 7-8.5 8.5-5-5L2 17"></path></svg>',
                'card_title_eng' => "Barter Increases Sales",
                'card_description_eng' => "Supertrade markets your company to local and national businesses, giving you access to potential customers, over and above your daily cash-paying clients. Your company will make incremental sales because of the demand of the buyers looking for barter opportunities from within the trade network.",
                'card_btn_text_eng' => "Learn More",
                'newsletter_title_eng' => null,
                'newsletter_sub_title_eng' => null,
                'newsletter_btn_text_eng' => null,
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'card_title_fr' => null,
                'card_description_fr' => null,
                'card_btn_text_fr' => null,
                'newsletter_title_fr' => null,
                'newsletter_sub_title_fr' => null,
                'newsletter_btn_text_fr' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
             [
                'language' => 'english',
                'section' => 'card',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'image' => "https://superinternaute.netlify.app/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fmember2.bfe2719d.jpg&w=3840&q=100",
                'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-dollar-sign md:w-10 md:h-10 w-6 h-6" aria-hidden="true"><line x1="12" x2="12" y1="2" y2="22"></line><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"></path></svg>',
                'card_title_eng' => "Barter Improves Cash Flow",
                'card_description_eng' => "There are two main ways to increase cash flow – more sales and reduced costs. Barter does both! Barter allows you to pay for what you need with what you have – allocating working capital for other needs. Using barter to purchase products/services reduces cash costs by paying for them with revenue generated by new barter sales.",
                'card_btn_text_eng' => "Learn More",
                'newsletter_title_eng' => null,
                'newsletter_sub_title_eng' => null,
                'newsletter_btn_text_eng' => null,
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'card_title_fr' => null,
                'card_description_fr' => null,
                'card_btn_text_fr' => null,
                'newsletter_title_fr' => null,
                'newsletter_sub_title_fr' => null,
                'newsletter_btn_text_fr' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'english',
                'section' => 'card',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'image' => "https://superinternaute.netlify.app/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fmember3.904ab680.jpg&w=640&q=100",
                'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-package md:w-10 md:h-10 w-6 h-6" aria-hidden="true"><path d="M11 21.73a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73z"></path><path d="M12 22V12"></path><polyline points="3.29 7 12 12 20.71 7"></polyline><path d="m7.5 4.27 9 5.15"></path></svg>',
                'card_title_eng' => "Barter Moves Excess Inventory & Fills Idle Production Time",
                'card_description_eng' => "When you join Supertrade, barter provides a tool to put that excess to use in profitable ways. We accomplish this by matching your product or service with businesses looking to purchase them on trade. It's a win-win situation.",
                'card_btn_text_eng' => "Learn More",
                'newsletter_title_eng' => null,
                'newsletter_sub_title_eng' => null,
                'newsletter_btn_text_eng' => null,
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'card_title_fr' => null,
                'card_description_fr' => null,
                'card_btn_text_fr' => null,
                'newsletter_title_fr' => null,
                'newsletter_sub_title_fr' => null,
                'newsletter_btn_text_fr' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'english',
                'section' => 'card',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'image' => "https://superinternaute.netlify.app/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fmember4.87c42243.jpg&w=3840&q=100",
                'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-zap md:w-10 md:h-10 w-6 h-6" aria-hidden="true"><path d="M4 14a1 1 0 0 1-.78-1.63l9.9-10.2a.5.5 0 0 1 .86.46l-1.92 6.02A1 1 0 0 0 13 10h7a1 1 0 0 1 .78 1.63l-9.9 10.2a.5.5 0 0 1-.86-.46l1.92-6.02A1 1 0 0 0 11 14z"></path></svg>',
                'card_title_eng' => "Barter Provides a Competitive Edge",
                'card_description_eng' => "Supertrade members patronize your establishment over the competition, because your Supertrade affiliation is an incentive to do business with you. Barter attracts new customers to your business, without affecting the existing cash sales already being generated by your company.",
                'card_btn_text_eng' => "Learn More",
                'newsletter_title_eng' => null,
                'newsletter_sub_title_eng' => null,
                'newsletter_btn_text_eng' => null,
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'card_title_fr' => null,
                'card_description_fr' => null,
                'card_btn_text_fr' => null,
                'newsletter_title_fr' => null,
                'newsletter_sub_title_fr' => null,
                'newsletter_btn_text_fr' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'english',
                'section' => 'card',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'image' => "https://superinternaute.netlify.app/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fmember5.665feba6.jpg&w=3840&q=100",
                'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-users md:w-10 md:h-10 w-6 h-6" aria-hidden="true"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"></path><path d="M16 3.128a4 4 0 0 1 0 7.744"></path><path d="M22 21v-2a4 4 0 0 0-3-3.87"></path><circle cx="9" cy="7" r="4"></circle></svg>',
                'card_title_eng' => "Barter Means New Cash Sales",
                'card_description_eng' => "That's not a misprint – yes, we said cash sales. If you perform a good job for a Supertrade client, they'll refer their cash-paying friends, clients, family and associates to you. Growing your business will always be tied directly to referrals from your happy customers.",
                'card_btn_text_eng' => "Learn More",
                'newsletter_title_eng' => null,
                'newsletter_sub_title_eng' => null,
                'newsletter_btn_text_eng' => null,
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'card_title_fr' => null,
                'card_description_fr' => null,
                'card_btn_text_fr' => null,
                'newsletter_title_fr' => null,
                'newsletter_sub_title_fr' => null,
                'newsletter_btn_text_fr' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
             [
                'language' => 'english',
                'section' => 'card',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'image' => "https://superinternaute.netlify.app/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fmember6.e3ed7c2c.jpg&w=640&q=100",
                'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-file-text md:w-10 md:h-10 w-6 h-6" aria-hidden="true"><path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z"></path><path d="M14 2v4a2 2 0 0 0 2 2h4"></path><path d="M10 9H8"></path><path d="M16 13H8"></path><path d="M16 17H8"></path></svg>',
                'card_title_eng' => "Barter Makes Record-Keeping Easy",
                'card_description_eng' => "Supertrade works much like a bank, providing control, record keeping, and administration for your barter activities. Using state-of-the-art technology, we track all of your barter sales/purchases and streamline the process, complete with easy-to-read itemized monthly statements.",
                'card_btn_text_eng' => "Learn More",
                'newsletter_title_eng' => null,
                'newsletter_sub_title_eng' => null,
                'newsletter_btn_text_eng' => null,
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'card_title_fr' => null,
                'card_description_fr' => null,
                'card_btn_text_fr' => null,
                'newsletter_title_fr' => null,
                'newsletter_sub_title_fr' => null,
                'newsletter_btn_text_fr' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'english',
                'section' => 'card',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'image' => "https://superinternaute.netlify.app/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fmember7.98d2fc58.jpg&w=640&q=100",
                'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-shield md:w-10 md:h-10 w-6 h-6" aria-hidden="true"><path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z"></path></svg>',
                'card_title_eng' => "Barter Means No Bad Debts",
                'card_description_eng' => "Supertrade trading takes the hassle out of collections. When you make a barter sale, call in advance for authorization verifying that the buyer has the available Trade Dollars. Then, upon order completion or delivery, call the office and customer service representative will post the trade, or log on the system and post it yourself. It's that simple.",
                'card_btn_text_eng' => "Learn More",
                'newsletter_title_eng' => null,
                'newsletter_sub_title_eng' => null,
                'newsletter_btn_text_eng' => null,
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'card_title_fr' => null,
                'card_description_fr' => null,
                'card_btn_text_fr' => null,
                'newsletter_title_fr' => null,
                'newsletter_sub_title_fr' => null,
                'newsletter_btn_text_fr' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'english',
                'section' => 'card',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'image' => "https://superinternaute.netlify.app/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fmember8.42b08f67.jpg&w=3840&q=100",
                'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-network md:w-10 md:h-10 w-6 h-6" aria-hidden="true"><rect x="16" y="16" width="6" height="6" rx="1"></rect><rect x="2" y="16" width="6" height="6" rx="1"></rect><rect x="9" y="2" width="6" height="6" rx="1"></rect><path d="M5 16v-3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v3"></path><path d="M12 12V8"></path></svg>',
                'card_title_eng' => "Barter Expands Distribution Channels",
                'card_description_eng' => "Supertrade's national affiliation with IRTA (International Reciprocal Trade Association), provides a convenient medium for local clients to trade with thousands of other businesses nationwide, expanding the possibilities for all involved. It opens the door to a broader range of products and services, as well as a greater marketing platform for your company.",
                'card_btn_text_eng' => "Learn More",
                'newsletter_title_eng' => null,
                'newsletter_sub_title_eng' => null,
                'newsletter_btn_text_eng' => null,
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'card_title_fr' => null,
                'card_description_fr' => null,
                'card_btn_text_fr' => null,
                'newsletter_title_fr' => null,
                'newsletter_sub_title_fr' => null,
                'newsletter_btn_text_fr' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'english',
                'section' => 'card',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'image' => "https://superinternaute.netlify.app/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fmember9.06998667.jpg&w=3840&q=100",
                'icon' => '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-target md:w-10 md:h-10 w-6 h-6" aria-hidden="true"><circle cx="12" cy="12" r="10"></circle><circle cx="12" cy="12" r="6"></circle><circle cx="12" cy="12" r="2"></circle></svg>',
                'card_title_eng' => "Barter Means Added Profits",
                'card_description_eng' => "With Supertrade, added profits are realized by the new customers barter provides. Sellers in a trade network make incremental barter sales (over and above their cash business) and increased sales mean increased profits.",
                'card_btn_text_eng' => "Learn More",
                'newsletter_title_eng' => null,
                'newsletter_sub_title_eng' => null,
                'newsletter_btn_text_eng' => null,
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'card_title_fr' => null,
                'card_description_fr' => null,
                'card_btn_text_fr' => null,
                'newsletter_title_fr' => null,
                'newsletter_sub_title_fr' => null,
                'newsletter_btn_text_fr' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'language' => 'france',
                'section' => 'card',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'image' => null,
                'icon' => null,
                'card_title_eng' => null,
                'card_description_eng' => null,
                'card_btn_text_eng' => null,
                'newsletter_title_eng' => null,
                'newsletter_sub_title_eng' => null,
                'newsletter_btn_text_eng' => null,
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'card_title_fr' => "Le troc augmente les ventes",
                'card_description_fr' => "Supertrade fait la promotion de votre entreprise auprès d'entreprises locales et nationales, vous donnant accès à des clients potentiels en plus de vos clients payant en espèces. Votre entreprise réalisera des ventes supplémentaires grâce à la demande des acheteurs recherchant des opportunités de troc au sein du réseau d’échange.",
                'card_btn_text_fr' => 'Learn More',
                'newsletter_title_fr' => null,
                'newsletter_sub_title_fr' => null,
                'newsletter_btn_text_fr' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
             [
                'language' => 'france',
                'section' => 'card',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'image' => null,
                'icon' => null,
                'card_title_eng' => null,
                'card_description_eng' => null,
                'card_btn_text_eng' => null,
                'newsletter_title_eng' => null,
                'newsletter_sub_title_eng' => null,
                'newsletter_btn_text_eng' => null,
                'heading_fr' => null,
                'sub_heading_fr' => "Le troc améliore la trésorerie",
                'card_title_fr' => "Il existe deux moyens principaux d'améliorer la trésorerie : augmenter les ventes et réduire les coûts. Le troc permet les deux ! Il vous permet d’obtenir ce dont vous avez besoin avec ce que vous possédez, en libérant ainsi des capitaux pour d'autres besoins. Acheter via le troc réduit les coûts en espèces grâce aux revenus générés par de nouvelles ventes en troc.",
                'card_description_fr' => null,
                'card_btn_text_fr' => 'Learn More',
                'newsletter_title_fr' => null,
                'newsletter_sub_title_fr' => null,
                'newsletter_btn_text_fr' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'france',
                'section' => 'card',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'image' => null,
                'icon' => null,
                'card_title_eng' => null,
                'card_description_eng' => null,
                'card_btn_text_eng' => null,
                'newsletter_title_eng' => null,
                'newsletter_sub_title_eng' => null,
                'newsletter_btn_text_eng' => null,
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'card_title_fr' => "Le troc écoule les excédents et comble les temps morts",
                'card_description_fr' => "Lorsque vous rejoignez Supertrade, le troc devient un outil utile pour valoriser vos excédents. Nous mettons en relation votre produit ou service avec des entreprises intéressées à les acheter en troc. Tout le monde y gagne !",
                'card_btn_text_fr' => 'Learn More',
                'newsletter_title_fr' => null,
                'newsletter_sub_title_fr' => null,
                'newsletter_btn_text_fr' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'france',
                'section' => 'card',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'image' => null,
                'icon' => null,
                'card_title_eng' => null,
                'card_description_eng' => null,
                'card_btn_text_eng' => null,
                'newsletter_title_eng' => null,
                'newsletter_sub_title_eng' => null,
                'newsletter_btn_text_eng' => null,
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'card_title_fr' => "Le troc offre un avantage concurrentiel",
                'card_description_fr' => "Les membres de Supertrade choisissent votre entreprise plutôt qu'une autre, car votre adhésion à Supertrade est un incitatif à faire affaire avec vous. Le troc attire de nouveaux clients sans nuire aux ventes en espèces que vous réalisez déjà.",
                'card_btn_text_fr' => 'Learn More',
                'newsletter_title_fr' => null,
                'newsletter_sub_title_fr' => null,
                'newsletter_btn_text_fr' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'france',
                'section' => 'card',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'image' => null,
                'icon' => null,
                'card_title_eng' => null,
                'card_description_eng' => null,
                'card_btn_text_eng' => null,
                'newsletter_title_eng' => null,
                'newsletter_sub_title_eng' => null,
                'newsletter_btn_text_eng' => null,
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'card_title_fr' => "Le troc génère de nouvelles ventes en espèces",
                'card_description_fr' => "Ce n’est pas une erreur – oui, nous parlons bien de ventes en espèces. Si vous rendez un bon service à un client Supertrade, il recommandera vos services à ses amis, clients et proches payant en espèces. La croissance de votre entreprise est directement liée à ces recommandations.",
                'card_btn_text_fr' => 'Learn More',
                'newsletter_title_fr' => null,
                'newsletter_sub_title_fr' => null,
                'newsletter_btn_text_fr' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
             [
                'language' => 'france',
                'section' => 'card',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'image' => null,
                'icon' => null,
                'card_title_eng' => null,
                'card_description_eng' => null,
                'card_btn_text_eng' => null,
                'newsletter_title_eng' => null,
                'newsletter_sub_title_eng' => null,
                'newsletter_btn_text_eng' => null,
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'card_title_fr' => null,
                'card_description_fr' => null,
                'card_btn_text_fr' => 'Learn More',
                'newsletter_title_fr' => null,
                'newsletter_sub_title_fr' => "Le troc simplifie la comptabilité",
                'newsletter_btn_text_fr' => "Supertrade fonctionne comme une banque, en assurant le suivi, la gestion et la comptabilité de vos échanges. Grâce à une technologie de pointe, nous enregistrons toutes vos transactions de troc et vous fournissons des relevés mensuels clairs et détaillés.",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'france',
                'section' => 'card',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'image' => null,
                'icon' => null,
                'card_title_eng' => null,
                'card_description_eng' => null,
                'card_btn_text_eng' => null,
                'newsletter_title_eng' => null,
                'newsletter_sub_title_eng' => null,
                'newsletter_btn_text_eng' => null,
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'card_title_fr' => "Le troc signifie zéro créance douteuse",
                'card_description_fr' => "Avec Supertrade, plus de soucis de recouvrement. Avant chaque vente, vous vérifiez que l’acheteur dispose du solde nécessaire en Dollars d’échange. Ensuite, il vous suffit de finaliser la commande et d’enregistrer la transaction via notre système. C’est simple et sécurisé.",
                'card_btn_text_fr' => 'Learn More',
                'newsletter_title_fr' => null,
                'newsletter_sub_title_fr' => null,
                'newsletter_btn_text_fr' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'france',
                'section' => 'card',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'image' => null,
                'icon' => null,
                'card_title_eng' => null,
                'card_description_eng' => null,
                'card_btn_text_eng' => null,
                'newsletter_title_eng' => null,
                'newsletter_sub_title_eng' => null,
                'newsletter_btn_text_eng' => null,
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'card_title_fr' => "Le troc étend les canaux de distribution",
                'card_description_fr' => "L’affiliation nationale de Supertrade à l’IRTA (International Reciprocal Trade Association) vous permet d’échanger avec des milliers d’entreprises à travers le pays, élargissant vos débouchés commerciaux et vos possibilités d’approvisionnement.",
                'card_btn_text_fr' => "Learn More",
                'newsletter_title_fr' => null,
                'newsletter_sub_title_fr' => null,
                'newsletter_btn_text_fr' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'france',
                'section' => 'card',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'image' => null,
                'icon' => null,
                'card_title_eng' => null,
                'card_description_eng' => null,
                'card_btn_text_eng' => null,
                'newsletter_title_eng' => null,
                'newsletter_sub_title_eng' => null,
                'newsletter_btn_text_eng' => null,
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'card_title_fr' => "Le troc augmente les profits",
                'card_description_fr' => "Grâce à Supertrade, les membres génèrent des ventes supplémentaires au-delà de leur activité traditionnelle. Plus de ventes signifient plus de profits, tout simplement.",
                'card_btn_text_fr' => "Learn More",
                'newsletter_title_fr' => null,
                'newsletter_sub_title_fr' => null,
                'newsletter_btn_text_fr' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'english',
                'section' => 'newsletter',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'image' => null,
                'icon' => null,
                'card_title_eng' => null,
                'card_description_eng' => null,
                'card_btn_text_eng' => null,
                'newsletter_title_eng' => "Ready to Get Started?",
                'newsletter_sub_title_eng' => "Join thousands of successful businesses already leveraging the power of Supertrade barter exchange.",
                'newsletter_btn_text_eng' => "Start Your Journey Today",
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'card_title_fr' => null,
                'card_description_fr' => null,
                'card_btn_text_fr' => null,
                'newsletter_title_fr' => null,
                'newsletter_sub_title_fr' => null,
                'newsletter_btn_text_fr' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'france',
                'section' => 'newsletter',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'image' => null,
                'icon' => null,
                'card_title_eng' => null,
                'card_description_eng' => null,
                'card_btn_text_eng' => null,
                'newsletter_title_eng' => null,
                'newsletter_sub_title_eng' => null,
                'newsletter_btn_text_eng' => null,
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'card_title_fr' => null,
                'card_description_fr' => null,
                'card_btn_text_fr' => null,
                'newsletter_title_fr' => "Prêt à commencer ?",
                'newsletter_sub_title_fr' => "Rejoignez des milliers d’entreprises prospères qui utilisent déjà la puissance du troc avec Supertrade.",
                'newsletter_btn_text_fr' => "Commencez votre aventure dès aujourd’hui",
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
