<?php

namespace Database\Seeders;

use App\Models\Faq;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class FaqSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Faq::insert([
            [
                'language' => 'english',
                'section' => 'heading',
                'heading_eng' => "What can we help with?",
                'sub_heading_eng' => "Learn about how barter can work for your business, from accounting to pricing.",
                'question_eng' => null,
                'answer_eng' => null,
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'question_fr' => null,
                'answer_fr' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'france',
                'section' => 'heading',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'question_eng' => null,
                'answer_eng' => null,
                'heading_fr' => "En quoi pouvons-nous vous aider ?",
                'sub_heading_fr' => "Découvrez comment le troc peut être bénéfique pour votre entreprise, de la comptabilité à la tarification.",
                'question_fr' => null,
                'answer_fr' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'english',
                'section' => 'faq',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'question_eng' => "Is barter the right solution for my company?",
                'answer_eng' => "Let’s discover this together. Ask yourself some questions.• Do we have excess inventory? Or inventory that we want to move?• Are we sitting with unsold products or services that are not currently contributing to our bottom line?• Do we want to increase business, gain new customers, develop new business and distribution channels? Most companies say “yes” in several of these categories and it is pretty easy to answer, “Sure – Absolutely we want all that.” Here is the hard question: If our company decides it wants to reduce costs and increase sales through the use of barter, are we willing to be committed to using barter as a form of payment for part of our operational purchases? If your answer is “no,” then a barter option may not be in your best interest. Are you a “yes?” or a “no?” That is the real question to ask.",
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'question_fr' => null,
                'answer_fr' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'english',
                'section' => 'faq',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'question_eng' => "Why does barter sometimes have a negative connotation?",
                'answer_eng' => "We love this question and it probably represents the one question that business people either try to be especially polite about, or that they blast off about – and for good reason. There are several answers to this question. Probably the most common reason is that some companies tend to over-promise and under deliver. Supertrade does the exact opposite; we under-promise and over-deliver. In addition, “unmanaged expectations” can be damaging to companies. The Trade Director helps clients gain a thorough understanding of what can be accomplished with barter and what is required to do so.",
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'question_fr' => null,
                'answer_fr' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'english',
                'section' => 'faq',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'question_eng' => "What should we consider before signing a contract with a barter exchange?",
                'answer_eng' => "Make sure you have your spending strategy in place and ask your barter company to sign off on that strategy. If they are not willing to do so, you may be gaining valuable information regarding future service and level of commitment in that hesitation.",
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'question_fr' => null,
                'answer_fr' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'english',
                'section' => 'faq',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'question_eng' => "Should we work with a barter exchange?",
                'answer_eng' => "The advantage to joining a barter company is that your options are immediately expanded to include new customers, new products, new services and new distribution channels. For instance, companies that employ barter as a critical sales avenue realize that cash-paying customers represent one business stream. But the real advantage of barter comes to life as the new distribution channels begin to deliver new customers. Turning excess capacity, unsold and sluggish inventory into revenue activates stalled areas of business and generates new revenue streams that carry to the bottom line.",
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'question_fr' => null,
                'answer_fr' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'english',
                'section' => 'faq',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'question_eng' => "How do I handle the accounting for my company’s corporate barter transactions?",
                'answer_eng' => "There are clear tax and accounting codes that provide answers to accounting questions and we encourage all companies to consult their financial resources to ensure accuracy. We refer companies to their respective financial departments and do not offer financial or tax advice.",
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'question_fr' => null,
                'answer_fr' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'english',
                'section' => 'faq',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'question_eng' => "Are there any tax advantages to bartering?",
                'answer_eng' => "Barter income is treated the same as cash income. There are neither tax advantages nor disadvantages to bartering. Trading is simply a method of payment and represents an additional means of generating revenue that would otherwise be unrealized in most cases.",
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'question_fr' => null,
                'answer_fr' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'english',
                'section' => 'faq',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'question_eng' => "What companies are involved in barter?",
                'answer_eng' => "Any company who has experienced the benefits of barter is likely to incorporate barter into its purchasing, business development and excess inventory management strategy. While there are varied estimates, it is widely known that most Fortune 500 companies recognize barter as an essential element of fiscal responsibility. Some estimate that the global barter industry has reached $65 billion annually while others cite the industry as a $10 or $20 billion influence. Over 500,000 businesses use barter to their competitive advantage. It is estimated that a minimum of 65% of Fortune 500 companies engage in barter.",
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'question_fr' => null,
                'answer_fr' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'english',
                'section' => 'faq',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'question_eng' => "How should I price my products and services?",
                'answer_eng' => "That depends on who you choose to work with. Some barter networks are based on MSRP while other trade at closer to street pricing. It’s critical to the success of your transaction to understand the “real value” of an exchange’s trade currency. The government looks at a trade dollar as equal to a cash dollar but it is important to ask yourself if the reality of the value you are receiving equates. The best way to explain this may be to simplify barter in the following way: Do not treat barter any differently than you would any cash transaction. Barter is simply a method of payment and all parties involved can and should still hold each other accountable, just as with any cash transaction. Check references; check reputations; check the company, just as you do for any other transaction. Your business decisions should not be altered in any way because of barter.",
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'question_fr' => null,
                'answer_fr' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'english',
                'section' => 'faq',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'question_eng' => "How do I incorporate barter into my budget and marketing plan?",
                'answer_eng' => "Some companies allow their marketing department to manage their barter transactions while some involve the CEO or CFO. When companies experience the full impact of barter, they often, very enthusiastically, initiate the process of examining budget and line item expenses that could be offset by trading instead of spending cash. Barter offers pragmatic and strategic opportunities to improve the budget; build the client base and distribution channels, increase sales, conserve cash spending and competitively position the success of the company’s future.",
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'question_fr' => null,
                'answer_fr' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'france',
                'section' => 'faq',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'question_eng' => null,
                'answer_eng' => null,
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'question_fr' => "Le troc est-il la solution idéale pour mon entreprise ?",
                'answer_fr' => "Voyons cela ensemble. Posez-vous quelques questions. • Avons-nous des stocks excédentaires ? Ou des stocks que nous souhaitons écouler ? • Avons-nous des produits ou services invendus qui ne contribuent pas actuellement à notre résultat net ? • Souhaitons-nous développer notre activité, conquérir de nouveaux clients, développer de nouveaux canaux de vente et de distribution ? La plupart des entreprises répondent « oui » à plusieurs de ces questions, et il est assez facile de répondre : « Bien sûr, absolument, nous voulons tout cela. » Voici la question difficile : si notre entreprise décide de réduire ses coûts et d’augmenter ses ventes grâce au troc, sommes-nous prêts à l’utiliser comme moyen de paiement pour une partie de nos achats opérationnels ? Si votre réponse est « non », le troc n’est peut-être pas dans votre intérêt. Êtes-vous un « oui » ou un « non » ? C’est la vraie question.",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'france',
                'section' => 'faq',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'question_eng' => null,
                'answer_eng' => null,
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'question_fr' => "Pourquoi le troc a-t-il parfois une connotation négative ?",
                'answer_fr' => "Nous adorons cette question, et c’est probablement celle sur laquelle les entrepreneurs essaient d’être particulièrement polis, ou sur laquelle ils s’emportent – et pour cause. Il existe plusieurs réponses à cette question. La raison la plus courante est probablement que certaines entreprises ont tendance à promettre trop et à ne pas tenir leurs promesses. Supertrade fait exactement le contraire. De plus, des « attentes non gérées » peuvent être préjudiciables aux entreprises. Le directeur commercial aide les clients à bien comprendre les possibilités offertes par le troc et les exigences pour y parvenir.",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'france',
                'section' => 'faq',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'question_eng' => null,
                'answer_eng' => null,
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'question_fr' => "Que faut-il prendre en compte avant de signer un contrat avec une plateforme de troc ?",
                'answer_fr' => "Assurez-vous d’avoir défini votre stratégie de dépenses et demandez à votre plateforme de troc de l’approuver. Si elle n’est pas disposée à le faire, cette hésitation pourrait vous permettre d’obtenir des informations précieuses sur le service futur et le niveau d’engagement.",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'france',
                'section' => 'faq',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'question_eng' => null,
                'answer_eng' => null,
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'question_fr' => "Devrions-nous travailler avec une plateforme de troc ?",
                'answer_fr' => "L'avantage de rejoindre une entreprise de troc est que vos options s'élargissent immédiatement pour inclure de nouveaux clients, de nouveaux produits, de nouveaux services et de nouveaux canaux de distribution. Par exemple, les entreprises qui utilisent le troc comme un canal de vente essentiel comprennent que les clients payant comptant représentent un flux d'activité. Mais le véritable avantage du troc se concrétise lorsque les nouveaux canaux de distribution commencent à attirer de nouveaux clients. Transformer les capacités excédentaires, les invendus et les stocks stagnants en revenus permet de dynamiser les secteurs d'activité en perte de vitesse et de générer de nouvelles sources de revenus qui impactent le résultat net.",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'france',
                'section' => 'faq',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'question_eng' => null,
                'answer_eng' => null,
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'question_fr' => "Comment gérer la comptabilité des transactions de troc de mon entreprise ?",
                'answer_fr' => "Il existe des codes fiscaux et comptables clairs qui répondent aux questions comptables et nous encourageons toutes les entreprises à consulter leurs ressources financières pour en garantir l’exactitude. Nous orientons les entreprises vers leurs services financiers respectifs et ne fournissons aucun conseil financier ou fiscal.",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'france',
                'section' => 'faq',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'question_eng' => null,
                'answer_eng' => null,
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'question_fr' => "Le troc présente-t-il des avantages fiscaux ?",
                'answer_fr' => "Les revenus du troc sont traités de la même manière que les revenus en espèces. Le troc ne présente ni avantages ni inconvénients fiscaux. Le commerce est simplement un moyen de paiement et représente un moyen supplémentaire de générer des revenus qui, autrement, ne seraient généralement pas réalisés.",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'france',
                'section' => 'faq',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'question_eng' => null,
                'answer_eng' => null,
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'question_fr' => "Quelles entreprises pratiquent le troc ?",
                'answer_fr' => "Toute entreprise ayant expérimenté les avantages du troc est susceptible d’intégrer cette pratique à sa stratégie d’achat, de développement commercial et de gestion des stocks excédentaires. Bien que les estimations varient, il est largement reconnu que la plupart des entreprises du Fortune 500 considèrent le troc comme un élément essentiel de la responsabilité fiscale. Certains estiment que le secteur mondial du troc atteint 65 milliards de dollars par an, tandis que d’autres le citent comme une influence de 25 milliards de dollars par an. Plus de 500 000 entreprises utilisent le troc pour améliorer leur compétitivité. On estime qu'au moins 65 % des entreprises du Fortune 500 y ont recours.",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'france',
                'section' => 'faq',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'question_eng' => null,
                'answer_eng' => null,
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'question_fr' => "Comment fixer le prix de mes produits et services ?",
                'answer_fr' => "Cela dépend de la personne avec laquelle vous choisissez de travailler. Certains réseaux de troc se basent sur le prix de vente conseillé, tandis que d’autres se rapprochent du prix de vente pratiqué. Il est essentiel pour la réussite de votre transaction de comprendre la « valeur réelle » de la monnaie d’échange d’une bourse. Le gouvernement considère qu’un dollar d’échange est équivalent à un dollar en espèces, mais il est important de se demander si la valeur réelle que vous recevez est équivalente. La meilleure façon d’expliquer cela est de simplifier le troc de la manière suivante : Ne traitez pas le troc différemment de toute transaction en espèces. Le troc est simplement un moyen de paiement et toutes les parties impliquées peuvent et doivent se tenir mutuellement responsables, comme pour toute transaction en espèces. Vérifiez les références, la réputation et l’entreprise, comme vous le faites pour toute autre transaction. Vos décisions commerciales ne doivent en aucun cas être influencées par le troc.",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'language' => 'france',
                'section' => 'faq',
                'heading_eng' => null,
                'sub_heading_eng' => null,
                'question_eng' => null,
                'answer_eng' => null,
                'heading_fr' => null,
                'sub_heading_fr' => null,
                'question_fr' => "Comment intégrer le troc à mon budget et à mon plan marketing ?",
                'answer_fr' => "Certaines entreprises confient la gestion de leurs transactions de troc à leur service marketing, tandis que d'autres impliquent le PDG ou le directeur financier. Lorsque les entreprises ressentent pleinement l'impact du troc, elles entament souvent, avec beaucoup d'enthousiasme, un processus d'analyse des dépenses budgétaires et des postes budgétaires qui pourraient être compensés par des transactions plutôt que par des dépenses en espèces. Le troc offre des opportunités pragmatiques et stratégiques pour améliorer le budget, développer la clientèle et les canaux de distribution, augmenter les ventes, maîtriser les dépenses et positionner l'entreprise de manière compétitive pour son avenir.",
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
